name: Deploy Script to Server

on:
  push:
    branches:
      - main  # Ou la branche que vous utilisez pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy script
      run: |
        scp /path/to/your/script.sh user@yourserver.com:/path/where/to/deploy/
        ssh user@yourserver.com 'bash -s' < /path/where/to/deploy/script.sh
