name: Deploy Script to Server

on:
  push:
    branches:
      - main  # Ou la branche que vous utilisez pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Transfer files to the server
      run: |
        scp -r ./path/to/your/files ${{ secrets.USERNAME }}@${{ secrets.HOST }}:./destination/path/on/server

    - name: Execute script on the server
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash ./destination/path/on/server/your_script.sh'
